version: '3.7'
provisioner-version: '1.0'
services:
  ${CONTAINER_NAME}:
    download-image: true
    registry_auth: true
    registry: ${REGISTRY}
    user: ${IAMUSER}
    password: ${IAMAPIKEY}
    image: ${IMAGE_NAME}
    environment:
      - HZN_ORG_ID=${HZN_ORG_ID}
      - HZN_DEVICE_ID=${HZN_DEVICE_ID}
      - HZN_NODE_ID=${HZN_DEVICE_ID}
      - HZN_NODE_POLICY=${HZN_NODE_POLICY}
      - HZN_EXCHANGE_USER_AUTH=${HZN_EXCHANGE_USER_AUTH}
      - HZN_VAR_RUN_BASE=${HZN_VAR_RUN_BASE}/${CONTAINER_NAME}
      - DOCKER_NAME=${CONTAINER_NAME}
      - ANAX_LOG_LEVEL=5
    ports:
      - 8510:8510
    volumes:
      - "/data/var/user/docker.sock:/var/run/docker.sock"
      - "/data/var/horizon:/data/var/horizon"
      - "/data/var/node.policy.json:${HZN_NODE_POLICY}"
      - "${HZN_VAR_RUN_BASE}/${CONTAINER_NAME}:${HZN_VAR_RUN_BASE}/${CONTAINER_NAME}"
    restart: always
    container_name: ${CONTAINER_NAME}

commands:
  ${CONTAINER_NAME}:
    init: "echo '{\"properties\": [{\"name\": \"${HZN_DEVICE_ID}\", \"value\": \"true\" }],\"constraints\": []}' > ${HZN_NODE_POLICY}"
    register: "sh -c 'hzn register -o ${HZN_ORG_ID} -u ${HZN_EXCHANGE_USER_AUTH} --policy ${HZN_NODE_POLICY}'"
    unregister: "hzn unregister -vf"
    stop: "sh -c 'hzn policy update --input-file=${HZN_NODE_POLICY}'"
    acoustics: "echo '{\"properties\": [{\"name\": \"microphone\", \"value\": \"pump\" }],\"constraints\": []}' > /tmp/pump-on.json && hzn policy update --input-file=/tmp/pump-on.json"
    mviedge: "echo '{\"properties\": [{\"name\": \"mviedge\", \"value\": \"nodered\" },{\"name\": \"mviedgedle\", \"value\": \"86\" }],\"constraints\": []}' > /tmp/mviedge.json && hzn policy update --input-file=/tmp/mviedge.json"
    sensortag: "echo '{\"properties\": [{\"name\": \"sensortag\", \"value\": \"nodered\" }],\"constraints\": []}' > /tmp/sensortag.json && hzn policy update --input-file=/tmp/sensortag.json"
    gps: "echo '{\"properties\": [{\"name\": \"sensors\", \"value\": \"gps\" }],\"constraints\": []}' > /tmp/gps.json && hzn policy update --input-file=/tmp/gps.json"
    sensorproxy: "echo '{\"properties\": [{\"name\": \"sensors\", \"value\": \"all\" }],\"constraints\": []}' > /tmp/sensorproxy.json && hzn policy update --input-file=/tmp/sensorproxy.json"
    samsung-demo: "echo '{\"properties\": [{\"name\": \"openhorizon.allowPrivileged\", \"value\": \"true\" }],\"constraints\": [], \"deployment\": {\"properties\": [{\"name\": \"auto-dock\", \"value\": \"Auto Dock\" },{\"name\": \"mms-agent\", \"value\": \"MMS Agent\" },{\"name\": \"samsung-demo\", \"value\": \"Samsung Demo\" },{\"name\": \"worker-safety\", \"value\": \"Worker Safety\" },{\"name\": \"liquid-prep\", \"value\": \"Liquid Prep\" }]}}' > /tmp/samsungdemo.json && hzn policy update --input-file=/tmp/samsungdemo.json"
    auto-dock: "echo '{\"properties\": [{\"name\": \"openhorizon.allowPrivileged\", \"value\": \"true\" }],\"constraints\": [], \"deployment\": {\"properties\": [{\"name\": \"auto-dock\", \"value\": \"Auto Dock\" }]}}' > /tmp/autodock.json && hzn policy update --input-file=/tmp/autodock.json"
    liquidprep: "echo '{\"properties\": [{\"name\": \"openhorizon.allowPrivileged\", \"value\": \"true\" }],\"constraints\": [], \"deployment\": {\"properties\": [{\"name\": \"liquid-prep\", \"value\": \"Liquid Prep\" }]}}' > /tmp/liquidprep.json && hzn policy update --input-file=/tmp/liquidprep.json"
    mvireg: "sh -c 'hzn exchange node addpolicy --json-file=/tmp/mviedge.json ${HZN_NODE_ID}'"
    fast: "sh -c 'hzn exchange node update --json-file=/tmp/node-fast.json ${HZN_NODE_ID}'"
    slow: "sh -c 'hzn exchange node update --json-file=/tmp/node-slow.json ${HZN_NODE_ID}'"
